Genome_fasta : /path/to/mm10.fa
Gene_anontation_bed12 : /path/to/gencode.vM16.annotation.bed12
GT_AG_U2_5 : /path/to/mm10_GT_AG_U2_5.good.matrix
GT_AG_U2_3 : /path/to/mm10_GT_AG_U2_3.good.matrix
conservation_bigwig : /path/to/mm10.60way.phyloP60way.bw
working_directory : /path/to/MicroExonator/
ME_DB : /path/to/VastDb.bed12
ME_len : 30
filter_method : legacy_mixture
Optimize_hard_drive : F
min_number_files_detected : 2

# Whippet

whippet_bin_folder : /path/to/Whippet.jl/bin
julia : /path/to/julia
Gene_anontation_GTF : /path/to/gencode.vM16.annotation.gtf
whippet_delta : whippet_delta.yaml
