Genome_fasta : /path/to/danRer11.fa
Gene_anontation_bed12 : /path/to/darRer11.Ensembl.genes.bed12
GT_AG_U2_5 : /path/to/danRer11_GT_AG_U2_5.good.matrix
GT_AG_U2_3 : /path/to/danRer11_GT_AG_U2_3.good.matrix
conservation_bigwig : NA
ME_len : 30
filter_method : legacy_mixture
working_directory : /path/to/MicroExonator/
ME_DB : /path/to/VastDb.bed12
Optimize_hard_drive : F
min_number_files_detected : 2

#Whippet

downstream_only : F
whippet_bin_folder : /path/to/Whippet.jl/bin
julia : /path/to/julia
Gene_anontation_GTF : /path/to/Danio_rerio.GRCz11.96.chr.gtf.UCSC_style
delta_method : whippet
whippet_delta : whippet_delta.yaml
