Genome_fasta : /path/to/Caenorhabditis_elegans.WBcel235.dna.fa
Gene_anontation_bed12 : /path/to/ce11.Ensembl.genes.bed12.Ensembl
GT_AG_U2_5 : NA
GT_AG_U2_3 : NA
conservation_bigwig : NA
working_directory : /path/to/MicroExonator/
ME_DB : /path/to/empty_DB
ME_len : 30
filter_method : legacy_mixture
Optimize_hard_drive : F
min_number_files_detected : 2

#Whippet

downstream_only : F
whippet_bin_folder : /path/to/Whippet.jl/bin
julia : /path/to/julia
Gene_anontation_GTF : /path/to/Caenorhabditis_elegans.WBcel235.gtf
whippet_delta : whippet_delta.yaml
