Genome_fasta : /path/to/hg19.fa
Gene_anontation_bed12 : /path/to/gencode.v19.chr_patch_hapl_scaff.annotation.bed12
GT_AG_U2_5 : /path/to/hg19_GT_AG_U2_5.good.matrix
GT_AG_U2_3 : /path/to/hg19_GT_AG_U2_3.good.matrix
conservation_bigwig : /path/to/hg19.100way.phyloP100way.bw
working_directory : /path/to/MicroExonator/
ME_DB : /path/to/hg19.VastDb.bed12
ME_len : 30
filter_method : legacy_mixture
Optimize_hard_drive : F
min_number_files_detected : 3


# Whippet

downstream_only : T
Only_whippet : T
whippet_bin_folder : /path/to/Whippet.jl/bin
julia : /path/to/julia
Gene_anontation_GTF : /path/to/gencode.v19.chr_patch_hapl_scaff.annotation.gtf
whippet_delta : whippet_delta.yaml
